name: Testing

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - "docs/**"
      - "package.json"
      - "package-lock.json"

env:
  NODE_OPTIONS: "--max_old_space_size=7168"

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
          cache: "npm"


      - run: |
          npm ci
          npm exec vue-tsc --noEmit
